server:
  port: 80
spring:
  application:
    name:gateway-server
  cloud:
    nacos:
      discovery:
        server-addr: 111.67.200.175:8848
    #      server-addr:nacos-server:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: admin-service_router
          uri: lb://admin-service
          predicates:
            - path=/admin/**
        - id: test_router
          uri: http://www.baidu.com
          predicates:
            - path=/test